### ISSUE TITLE
Error when drawing from multiple walker files

### ISSUE THREAD

**Issue by villrv** [guillochon/MOSFiT#105]
When giving a list of walker files (e.g. "-w walker1.json walker2.json"), mosfit seems to load in all the files but only draws from the first file in the list.

**Comment by guillochon** [comment]
This is not really a bug but just the previous default behavior where walkers would be drawn from all walker files sequentially, not drawing from the second file until all walkers from the first file had been exhausted.

Now, in https://github.com/guillochon/MOSFiT/pull/109, walkers will be drawn in a "riffled" fashion, cycling between files. At the moment all the walker files need to have the same number of walkers otherwise the riffling won't work, this is being worked on.

**Comment by guillochon** [comment]
Should be done in https://github.com/guillochon/MOSFiT/commit/5210b1aeda057adf5315e5280bca5d6cc5d186c9, closing.
